name: Maven

on: [push, pull_request]

jobs:
  build:

    strategy:
      matrix:
        os: [ubuntu-24.04]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: swift build && swift test

